// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tomogoma/usersms/pkg/api/status.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/tomogoma/usersms/pkg/api/status.proto

It has these top-level messages:
	Request
	Response
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	APIKey string `protobuf:"bytes,1,opt,name=APIKey" json:"APIKey,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetAPIKey() string {
	if m != nil {
		return m.APIKey
	}
	return ""
}

type Response struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version       string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CanonicalName string `protobuf:"bytes,4,opt,name=canonicalName" json:"canonicalName,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetCanonicalName() string {
	if m != nil {
		return m.CanonicalName
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Response)(nil), "api.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Status service

type StatusClient interface {
	Check(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type statusClient struct {
	c           client.Client
	serviceName string
}

func NewStatusClient(serviceName string, c client.Client) StatusClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "api"
	}
	return &statusClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *statusClient) Check(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Status.Check", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Status service

type StatusHandler interface {
	Check(context.Context, *Request, *Response) error
}

func RegisterStatusHandler(s server.Server, hdlr StatusHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Status{hdlr}, opts...))
}

type Status struct {
	StatusHandler
}

func (h *Status) Check(ctx context.Context, in *Request, out *Response) error {
	return h.StatusHandler.Check(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/tomogoma/usersms/pkg/api/status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0xad, 0xa9, 0x8e, 0xf6, 0x32, 0x07, 0x09, 0x9e, 0x6a, 0x10, 0xf1, 0x94, 0x15,
	0x7d, 0x02, 0xf1, 0x24, 0x82, 0x48, 0x7c, 0x82, 0xe9, 0x76, 0x48, 0x97, 0xba, 0x3b, 0x6b, 0x66,
	0x23, 0x78, 0xf3, 0xd1, 0x25, 0x6b, 0x04, 0x7b, 0xdb, 0xff, 0xfb, 0x7f, 0x96, 0x6f, 0xc0, 0x74,
	0x2e, 0x6d, 0x87, 0x75, 0x63, 0xc5, 0x9b, 0x24, 0x5e, 0x3a, 0xf1, 0x64, 0x94, 0x79, 0xe3, 0xd5,
	0xc4, 0x5d, 0x67, 0x28, 0x3a, 0xa3, 0x89, 0xd2, 0xa0, 0x4d, 0xec, 0x25, 0x09, 0xce, 0x28, 0xba,
	0xfa, 0x12, 0x16, 0x2d, 0x7f, 0x0c, 0xac, 0x09, 0xcf, 0xa1, 0x7c, 0x78, 0x7d, 0x7a, 0xe6, 0xaf,
	0xaa, 0x58, 0x15, 0x37, 0x27, 0xed, 0x94, 0xea, 0xef, 0x02, 0x8e, 0x5b, 0xd6, 0x28, 0x41, 0x19,
	0x11, 0xe6, 0x81, 0x3c, 0x4f, 0x93, 0xfc, 0xc6, 0x0a, 0x16, 0x9f, 0xdc, 0xab, 0x93, 0x50, 0x1d,
	0x66, 0xfc, 0x17, 0x71, 0x05, 0xa7, 0x1b, 0x56, 0xdb, 0xbb, 0x98, 0xc6, 0x76, 0x96, 0xdb, 0xff,
	0x08, 0xaf, 0x60, 0x69, 0x29, 0x48, 0x70, 0x96, 0xde, 0x5f, 0xc6, 0x8f, 0xe7, 0x79, 0xb3, 0x0f,
	0xef, 0x6e, 0xa1, 0x7c, 0xcb, 0xea, 0x78, 0x0d, 0x47, 0x8f, 0x5b, 0xb6, 0x3b, 0x3c, 0x6b, 0x28,
	0xba, 0x66, 0x72, 0xbf, 0x58, 0x4e, 0xe9, 0xd7, 0xb2, 0x3e, 0x58, 0x97, 0xf9, 0xc6, 0xfb, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x0c, 0xbf, 0x4b, 0x16, 0x01, 0x00, 0x00,
}
