#!/usr/bin/env bash
NAME="usersms"
VERSION="0.1.0"
DESCRIPTION="User profile management micro-service"
CANONICAL_NAME="usersmsv0"
CONF_DIR="/etc/usersms"
CONF_FILE="/etc/usersms/usersmsv0.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/usersmsv0"
UNIT_NAME="usersmsv0.service"
UNIT_FILE="/etc/systemd/system/usersmsv0.service"
DOCS_DIR="/etc/usersms/docs"
